name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app on gh pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Setup dependencies
        run: npm ci
      - name: Deploy app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
